name: interpart-backend
recipe: mean
config:
  node: 12 
  database: mariadb
  port: '3000' 
  ssl: true
  scanner: false
  portforward: true
  globals:
    '@loopback/cli': latest
#services:
#  mysql:
#    type: mariadb
#    portforward: true
#    creds:
#      user: interpart
#      password: interpart
#      database: interpartdb
#  node:
#    scanner: false
#    #ports:
#    #  - '127.0.0.1::3000'
#  database:
#    type: mongo
#    scanner: false
#    #portforward: 9000
#    #config:
#    #  database: custom.conf
tooling:
  lb4: 
    service: appserver
  npm:
    service: appserver
  yarn:
    service: appserver
